Repository DroneDB/DroneDB, pull requests merged in 2021-01, with the labels that each got.

#153 Added tile C-bindings
  nodejs/ne_functions.cc
  src/ddb.cpp
  src/ddb.h
Labels: enhancement

#154 Updated Docs
  .github/workflows/docs.yml
  docs/_static/favicon.ico
  docs/index.rst
Labels: enhancement

#156 Added tileUrl
  nodejs/js/dataset.js
  nodejs/js/fetchEntries.js
  nodejs/js/thumbs.js
  nodejs/js/utils.js
Labels: enhancement

#157 Support for tiling geoprojectable geoimages
  src/cmd/tile.cpp
  src/entry.cpp
  src/entry.h
  src/geoproject.cpp
  src/geoproject.h
  src/tiler.cpp
  src/tiler.h
Labels: enhancement

#159 Fix chunked upload progress
  src/chunkeduploadclient.cpp
  src/chunkeduploadclient.h
  src/cmd/share.cpp
  src/net/request.cpp
  src/shareservice.cpp
Labels: enhancement, software fault

#160 Support for inline downloads, added helper
  nodejs/js/dataset.js
  nodejs/js/utils.js
Labels: enhancement

#161 Geoprojection bug fix
  src/cmd/geoproj.cpp
  src/geoproject.cpp
  src/geoproject.h
  src/tiler.cpp
Labels: software fault

#162 Add markdown support
  .vscode/settings.json
  nodejs/js/entry.js
  src/entry.cpp
  src/entry_types.cpp
  src/entry_types.h
Labels: enhancement

#163 Fix docs workflow
  .github/workflows/docs.yml
Labels: enhancement

#166 Fix tiler on windows
  src/tiler.cpp
  src/tiler.h
  test/ddb_test.cpp
  test/tiler_test.cpp
Labels: enhancement, software fault

#168 Fix geoproj batch processing
  src/cmd/geoproj.cpp
  src/geoproject.cpp
  src/geoproject.h
Labels: software fault

#169 Add support for license/readme detection
  src/database.cpp
Labels: enhancement

#170 Fix markdown detection
  src/entry.cpp
Labels: software fault

#171 getFileContents support
  nodejs/js/dataset.js
  nodejs/js/registry.js
Labels: enhancement
