Repository DroneDB/DroneDB, pull requests merged in 2021-06, with the labels that each got.

#231 Read DJI's XMP lat/lon tags
  src/exif.cpp
  test/dsmservice_test.cpp
Labels: software fault

#234 Refactor of moveEntry and fixes + tests
  src/dbops.cpp
  test/ddb_test.cpp
Labels: enhancement, software fault

#229 Improve js support fs
  nodejs/js/dataset.js
  nodejs/js/pathutils.js
  nodejs/js/registry.js
  src/dbops.cpp
Labels: enhancement

#240 Fix thumbnail path encoding
  nodejs/js/dataset.js
Labels: software fault

#241 Update mtime values when cloning/pulling
  src/dbops.cpp
  src/dbops.h
  src/delta.h
  src/mio.cpp
  src/mio.h
  src/registry.cpp
  test/fs_test.cpp
Labels: software fault
